name: ctp_mobile
description: "CTP 2.0 project powered by SSA Group."
publish_to: 'none'
version: 2.0.1+33

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # 0.0.1
  mobile_kit:
    path: ../mobile_kit/mobile_kit
  dartz: 0.10.1
  firebase_messaging: 16.1.1
  freezed_annotation: 3.1.0
  dio: ^5.8.0
  pretty_dio_logger: ^1.4.0
  json_annotation: 4.9.0
  jwt_decoder: ^2.0.1
  retrofit: 4.7.2

dev_dependencies:
  analyzer: ^8.1.1
  build_runner: 2.8.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: 6.11.1
  retrofit_generator: 10.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
